# Generated by Django 4.2.28 on 2026-02-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('specs', models.TextField(help_text='One per line')),
                ('icon', models.CharField(choices=[('CameraIcon', 'CameraIcon'), ('FingerPrintIcon', 'FingerPrintIcon'), ('BoltIcon', 'BoltIcon'), ('ShieldCheckIcon', 'ShieldCheckIcon')], default='CameraIcon', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DistributorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Sole Distributor of ZK biometric devices in Pakistan', max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Contact Us for Bulk Orders', max_length=50)),
                ('button_link', models.CharField(default='/contact', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Distributor Info',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('DevicePhoneMobileIcon', 'DevicePhoneMobileIcon'), ('ChartBarIcon', 'ChartBarIcon'), ('ShieldCheckIcon', 'ShieldCheckIcon')], default='DevicePhoneMobileIcon', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city_state_zip', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Office Addresses',
                'ordering': ['order'],
            },
        ),
    ]
