# Generated by Django 4.2.28 on 2026-02-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city_state_zip', models.CharField(max_length=255)),
                ('sales_phone', models.CharField(max_length=50)),
                ('support_phone', models.CharField(max_length=50)),
                ('info_email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(max_length=254)),
                ('hours_weekday', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('hours_saturday', models.CharField(default='10:00 AM - 2:00 PM', max_length=100)),
                ('hours_sunday', models.CharField(default='Closed', max_length=100)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
