# Generated by Django 4.2.28 on 2026-02-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon_name',
            field=models.CharField(default='BriefcaseIcon', help_text="Name of the Heroicon (e.g., 'UserGroupIcon')", max_length=50),
            preserve_default=False,
        ),
    ]
